version: '3.9'
services:
  locator_app:
    container_name: locator_app
    build:
      context: ../.
      dockerfile: ./docker/Dockerfile
    image: 'geolocator:latest'
    ports:
      - 8080:8080
    depends_on:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: locatordb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: